### ISSUE TITLE
Using vl53l1x with external power source

### ISSUE THREAD

**Issue by AlanWalker97** [pimoroni/vl53l1x-python#31]
Hi. When i'm trying to use my vl53l1x sensor with external power source, i always get this error:

Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 232, in 'calling callback function'
  File "/usr/local/lib/python2.7/dist-packages/VL53L1X.py", line 134, in _i2c_write
    self._i2c.i2c_rdwr(msg_w)
  File "/usr/local/lib/python2.7/dist-packages/smbus2/smbus2.py", line 637, in i2c_rdwr
    ioctl(self.fd, I2C_RDWR, ioctl_data)
OSError: [Errno 121] Remote I/O error

So can i use sensor with external power source or is this problem relevant with the library?

**Comment by Gadgetoid** [comment]
How are you wiring up/powering your sensor? This error indicates a low-level failure to communicate with the sensor, suggesting a wiring/electrical issue.
